[project]
name = "end-to-end1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "quantulum3>=0.9.2",
    "scikit-learn>=1.6.1",
    "sentence-transformers>=4.1.0",
    "setuptools>=80.7.1",
]
